### PR TITLE
Add Allowed Timeframes to Websockets

### PR DESCRIPTION
**Pull request by timetraveler328**

### CODE REVIEW

**Review by teambailey — APPROVED** [review]

**Review by mmoghaddam385 — COMMENTED** [review]
Our delayed server supports `T`, `Q`, `A` and `AM` delayed feeds, should all of those paths include the delayed timeframes?

**Comment by timetraveler328** [comment]
> Our delayed server supports `T`, `Q`, `A` and `AM` delayed feeds, should all of those paths include the delayed timeframes?

Hmm let me chat with Peter when he gets in, I think some wires are crossed about our delayed ws products.  I was going by https://polygon.io/stocks#compare which makes it seem like only minute aggs are available for delayed feed

**Comment by mmoghaddam385** [comment]
> > Our delayed server supports `T`, `Q`, `A` and `AM` delayed feeds, should all of those paths include the delayed timeframes?
> 
> Hmm let me chat with Peter when he gets in, I think some wires are crossed about our delayed ws products. I was going by https://polygon.io/stocks#compare which makes it seem like only minute aggs are available for delayed feed

I believe we support all of those delayed channels for enterprise delayed.feed customers, but don't advertise them to personal subscribers. Peter would know better though 👍

**Comment by timetraveler328** [comment]
> > > Our delayed server supports `T`, `Q`, `A` and `AM` delayed feeds, should all of those paths include the delayed timeframes?
> > 
> > 
> > Hmm let me chat with Peter when he gets in, I think some wires are crossed about our delayed ws products. I was going by https://polygon.io/stocks#compare which makes it seem like only minute aggs are available for delayed feed
> 
> I believe we support all of those delayed channels for enterprise delayed.feed customers, but don't advertise them to personal subscribers. Peter would know better though 👍

I spoke with Peter, we're going to treat A and AM the same and update the product comparison (and I've added delayed to allowed timeframes in the spec for A).  T and Q will need to change behavior, I've put a BE ticket in the backlog for that.

**Review by mmoghaddam385 — APPROVED** [review]

**Pull request merged**
