### PR TITLE
add enum for tickers sort field

### PR DESCRIPTION
**Pull request by suremarc**

### CODE REVIEW

**Comment by jbonzo** [comment]
@mmoghaddam385 Could you also sort by cusip?

**Comment by mmoghaddam385** [comment]
> @mmoghaddam385 Could you also sort by cusip?
> 
> Our current behavior is to sort by anything but is that too open? It's easy to get a 500 if you sort by the wrong thing.

@jbonzo yes you can sort by CUSIP if you want (not that it's very meaningful)

and you're right we should not 500 if you sort by the wrong thing (I don't think it's bad to be able to sort on anything though)

**Comment by jbonzo** [comment]
> > @mmoghaddam385 Could you also sort by cusip?
> > Our current behavior is to sort by anything but is that too open? It's easy to get a 500 if you sort by the wrong thing.
> 
> @jbonzo yes you can sort by CUSIP if you want (not that it's very meaningful)
> 
> and you're right we should not 500 if you sort by the wrong thing (I don't think it's bad to be able to sort on anything though)

@mmoghaddam385 Just seems harder to maintain. I think we thought of a solution to do it I just don't know if its fruitful. We could just take what's in the spec and only allow to sort on that.

**Comment by jbonzo** [comment]
> > > @mmoghaddam385 Could you also sort by cusip?
> > > Our current behavior is to sort by anything but is that too open? It's easy to get a 500 if you sort by the wrong thing.
> > 
> > 
> > @jbonzo yes you can sort by CUSIP if you want (not that it's very meaningful)
> > and you're right we should not 500 if you sort by the wrong thing (I don't think it's bad to be able to sort on anything though)
> 
> @mmoghaddam385 Just seems harder to maintain. I think we thought of a solution to do it I just don't know if its fruitful. We could just take what's in the spec and only allow to sort on that.

@suremarc could you also make a PR to reference tickers only allowing to sort on the fields specified in this PR. 400 if not.

**Review by jbonzo — APPROVED** [review]

**Pull request merged**
